//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUniversidad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Carrera_Materia
    {
        public int ID { get; set; }
        public Nullable<int> id_Materia { get; set; }
        public Nullable<int> id_Carrera { get; set; }
    
        public virtual Table_Carreras Table_Carreras { get; set; }
        public virtual Table_Materias_DB Table_Materias_DB { get; set; }
    }
}
