//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUniversidad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Materias_DB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Materias_DB()
        {
            this.Table_Materia__Alumno = new HashSet<Table_Materia__Alumno>();
            this.Table_Materias_Profe = new HashSet<Table_Materias_Profe>();
            this.Table_Carrera_Materia = new HashSet<Table_Carrera_Materia>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> id_Alumno { get; set; }
        public Nullable<int> id_Profesor { get; set; }
        public Nullable<int> id_Carrera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Materia__Alumno> Table_Materia__Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Materias_Profe> Table_Materias_Profe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Carrera_Materia> Table_Carrera_Materia { get; set; }
    }
}
